# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20171009_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panelrequesttype",
            name="panel_type",
            field=models.IntegerField(
                choices=[
                    (0, "Panel"),
                    (1, "Blackout"),
                    (2, "Convention Event"),
                    (3, "Convention Ops"),
                ],
                default=0,
            ),
        ),
    ]
