version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Low risk - merge without much review
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Higher risk - review more carefully
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/registration/frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    groups:
      # Low risk - merge without much review
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Higher risk - review more carefully
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"