language: python
dist: focal
before_install:
- sudo apt-get -y install xfonts-75dpi xfonts-base python3-psycopg2
- wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
- sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
- sudo apt-get -y -f install
#- sudo ln  -s /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf
addons:
  apt:
    packages:
    - swig
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- 3.7
- 3.8
env:
- DJANGO_PACKAGE="Django>=1.11,<1.12"
install:
- pip install --upgrade pip wheel
- pip install -r requirements.txt
- pip install coveralls
- pip freeze
- cp fm_eventmanager/settings.py.travis fm_eventmanager/settings.py
script:
- coverage run manage.py test registration
- coverage report
after_success:
- coveralls
notifications:
  slack:
    secure: UZslI3os7aroDE6bedB8Iezt+ZRsqTKrgW6F9R9ymIFstM3a4OtYJwFcFb7tqwBtbTE1pkuHgPVUFnkiTzZBUP+h9mNudA4Pc4/5mSw9DCFm+L82Vq7rP6IkYaE+LeUCljSaS+dEI6f6v2wtANHkxVmP3pKyy3CKwWVdTbmTrHSYbAU6IY7xj2mlaJ3fvIUVAqbWIvNjS8DTxuax8aI9hwEu66mDEr1Or0ugrLFMwe4E5N9prAA/qYw9YTfZJC9Bj/xCHauGWqB3PkVySce13MJZooJLiFMB7/nJIxpZCzNgkfB+pmdGsN8G6LucUAd9+2SS8gwuazQkiiSUWDm6GF618fmbBr3ZL2IcVNOGox9+NwB4WYHae9T9+ZX1omVBuLtOqaAM0ZeYb4Np+5aIuySYkHLT+qCxzzAOIm4tPnhaTUSmJnI7uLWLiX4UL9SVE36vwc2cOkIT6GmI0uBsePZC/wm6xZTStSrqqVJdw3mVbOYx+h9yfuFuI4vZerVNssCoFAeTCt8OWr1ydfKYOY1D3CmzlN1IGHO9uw+55kXDYK2Xfl7806X5s8pG5OvF6Yc7H8lAg8ft/TO28xxptAS54YgINkYIVc0oIK/8oNtRXWiGAsiNGTQltGLmc8fFk3bNVMCyLBKU6a68umdT43PLzCphQb4h7nCqgg4oUcE=
