language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages:
      - swig

# Save pip's downloads/packages/wheels between job runs
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
env:
  - DJANGO_PACKAGE="Django>=1.11,<1.12"

matrix:
    exclude:
       - python 2.7

install:
  - pip install --upgrade pip wheel
  - pip install --pre -e .$EXTRAS
  - pip install -r requirements.txt
  - pip freeze
script: ./manage.py test registration
