language: python

dist: xenial

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
before_install:
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.xenial_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.5-1.xenial_amd64.deb

addons:
  apt:
    packages:
      - swig

# Save pip's downloads/packages/wheels between job runs
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 2.7
env:
  - DJANGO_PACKAGE="Django>=1.11,<1.12"

matrix:
    exclude:
       - python 2.7

install:
  - pip install --upgrade pip wheel
  - pip install -r requirements.txt
  - pip install coveralls
  - pip freeze
  - cp fm_eventmanager/settings.py.travis fm_eventmanager/settings.py
script:
  - coverage run manage.py test registration
  - coverage report
after_success:
  - coveralls
