version: '2'
services:
  app:
    image: apis:latest
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./registration:/app/registration
      - ./fm_eventmanager/settings.py.docker:/app/fm_eventmanager/settings.py
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
