[supervisord]
nodaemon=true

[program:gunicorn]
command=uv run gunicorn fm_eventmanager.asgi:application -k fm_eventmanager.worker.ApisWorker --bind unix:/tmp/apis.sock
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=1
autorestart=false

[program:nginx]
command=/usr/sbin/nginx -c /app/nginx.conf
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stopsignal=QUIT
startsecs=1
autorestart=false

[eventlistener:quit_on_failure]
events=PROCESS_STATE_STOPPED,PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
command=bash -c "printf 'READY\n' && while read line; do kill -SIGQUIT $PPID; done < /dev/stdin"
