# Generated by Django 6.0.5 on 2026-07-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
    ]
