# Generated by Django 6.0.5 on 2026-07-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffposition_position_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffposition',
            name='event',
        ),
    ]
