# Generated by Django 6.0.5 on 2026-07-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffposition_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffposition',
            name='is_open',
        ),
    ]
