# Generated by Django 6.0.5 on 2026-07-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="fandom_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
