# Generated by Django 6.0.6 on 2026-07-07 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0118_alter_staff_department_and_more"),
        ("staff", "0011_department_default_landing_page_staff_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffPosting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slots",
                    models.IntegerField(
                        default=1, help_text="Number of open positions for this posting"
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, verbose_name="Open for Applications"
                    ),
                ),
                (
                    "application_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional deadline for applications",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Event-specific notes or requirements for this posting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: link to a specific event. Leave blank for ongoing positions (e.g., Held Positions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_postings",
                        to="registration.event",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postings",
                        to="staff.staffposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "staff posting",
                "verbose_name_plural": "staff postings",
            },
        ),
        migrations.CreateModel(
            name="StaffApplicant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_first_name", models.CharField(max_length=200)),
                ("legal_last_name", models.CharField(max_length=200)),
                ("preferred_first_name", models.CharField(blank=True, max_length=200)),
                ("preferred_last_name", models.CharField(blank=True, max_length=200)),
                ("street_address_1", models.CharField(blank=True, max_length=200)),
                ("street_address_2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=200)),
                ("birthdate", models.DateField()),
                ("email_ok", models.BooleanField(default=False)),
                ("survey_ok", models.BooleanField(default=False)),
                ("registration_token", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this applicant"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="staff.staffposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "staff applicant",
                "verbose_name_plural": "staff applicants",
            },
        ),
        migrations.AddConstraint(
            model_name="staffposting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("position", "event"),
                name="unique_position_per_event",
            ),
        ),
    ]
