# Generated by Django 6.0.6 on 2026-07-07 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0012_staffposting_staffapplicant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
            },
        ),
    ]
