# Generated by Django 6.0.6 on 2026-07-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('change_fandom_name', 'Can change fandom/credit name')], 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
    ]
