# Generated by Django 6.0.6 on 2026-07-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0014_alter_staff_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="onboarding_complete",
            field=models.BooleanField(
                default=False,
                help_text="Has this staff member completed their onboarding process?",
            ),
        ),
    ]
