# Generated by Django 6.0.6 on 2026-07-07 22:37

from django.db import migrations, models

import registration.models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0015_staff_onboarding_complete"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=registration.models.get_registration_token,
                        max_length=200,
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                (
                    "ignore_time_window",
                    models.BooleanField(
                        default=False,
                        help_text="Enabling this option will allow this invite code to disregard the open and close date and time specified in the event. The Valid Until setting on this form will still apply",
                        verbose_name="Ignore Registration Time Window",
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Valid Until")),
                ("used", models.BooleanField(default=False)),
                (
                    "used_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Used Date"
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Staff Invite",
                "verbose_name_plural": "Staff Invites",
            },
        ),
    ]
