# Generated by Django 6.0.6 on 2026-07-07 22:37

from django.db import migrations


def copy_staff_invites(apps, schema_editor):
    """Copy data from registration_temp_token to staff_staffinvite"""
    # Get the old model from registration
    OldStaffInvite = apps.get_model("registration", "StaffInvite")
    # Get the new model from staff
    NewStaffInvite = apps.get_model("staff", "StaffInvite")

    # Copy all records
    for old_invite in OldStaffInvite.objects.all():
        NewStaffInvite.objects.create(
            token=old_invite.token,
            email=old_invite.email,
            ignore_time_window=old_invite.ignore_time_window,
            valid_until=old_invite.validUntil,
            used=old_invite.used,
            used_date=old_invite.usedDate,
            sent=old_invite.sent,
        )


def reverse_copy(apps, schema_editor):
    """Clear the new staff invites if rolling back"""
    NewStaffInvite = apps.get_model("staff", "StaffInvite")
    NewStaffInvite.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0016_staffinvite"),
        (
            "registration",
            "0118_alter_staff_department_and_more",
        ),  # Ensure registration is ready
    ]

    operations = [
        migrations.RunPython(copy_staff_invites, reverse_copy),
    ]
