# Generated by Django 6.0.6 on 2026-07-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_copy_staff_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Select a parent department if this is a sub-department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='staff.department', verbose_name='Parent Department'),
        ),
    ]
