# Generated by Django 6.0.6 on 2026-07-08 18:45

import django.db.models.deletion
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0119_badge_staff_badge_badge_attendee_or_staff_not_both'),
        ('staff', '0018_department_parent_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_token', models.CharField(default=registration.models.get_registration_token, max_length=200)),
                ('badge_name', models.CharField(blank=True, max_length=200)),
                ('twitter', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=200)),
                ('contact_relation', models.CharField(blank=True, max_length=200)),
                ('special_skills', models.TextField(blank=True)),
                ('special_food', models.TextField(blank=True)),
                ('special_medical', models.TextField(blank=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('need_room', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registrations', to='registration.event')),
                ('shirt_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.shirtsizes')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Event Registration',
                'verbose_name_plural': 'Staff Event Registrations',
                'unique_together': {('staff', 'event')},
            },
        ),
    ]
