# Generated by Django 6.0.6 on 2026-07-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_staffeventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffeventregistration',
            name='badge_name',
        ),
        migrations.RemoveField(
            model_name='staffeventregistration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffeventregistration',
            name='need_room',
        ),
    ]
