# Generated by Django 6.0.6 on 2026-07-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_staffeventregistration_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffeventregistration',
            name='badge',
        ),
    ]
