# Generated by Django 6.0.6 on 2026-07-17 08:49

from django.db import migrations, models
import registration.models


def populate_registration_tokens(apps, schema_editor):
    """Add registration tokens to existing staff without one"""
    Staff = apps.get_model('staff', 'Staff')
    for staff in Staff.objects.filter(registration_token=''):
        staff.registration_token = registration.models.get_registration_token()
        staff.save(update_fields=['registration_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_remove_staffeventregistration_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='registration_token',
            field=models.CharField(
                default=registration.models.get_registration_token,
                help_text='Unique token for event registration, rotates after each use',
                max_length=200
            ),
        ),
        migrations.RunPython(populate_registration_tokens, migrations.RunPython.noop),
    ]
