# Generated by Django 6.0.7 on 2026-07-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_add_registration_token_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffeventregistration',
            old_name='twitter',
            new_name='bluesky',
        ),
    ]
