/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrationOnsiteAdminRouteImport } from './routes/registration/onsite/admin'

const RegistrationOnsiteAdminRoute = RegistrationOnsiteAdminRouteImport.update({
  id: '/registration/onsite/admin',
  path: '/registration/onsite/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/registration/onsite/admin': typeof RegistrationOnsiteAdminRoute
}
export interface FileRoutesByTo {
  '/registration/onsite/admin': typeof RegistrationOnsiteAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/registration/onsite/admin': typeof RegistrationOnsiteAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/registration/onsite/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/registration/onsite/admin'
  id: '__root__' | '/registration/onsite/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RegistrationOnsiteAdminRoute: typeof RegistrationOnsiteAdminRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/registration/onsite/admin': {
      id: '/registration/onsite/admin'
      path: '/registration/onsite/admin'
      fullPath: '/registration/onsite/admin'
      preLoaderRoute: typeof RegistrationOnsiteAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RegistrationOnsiteAdminRoute: RegistrationOnsiteAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
