# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-30 14:09


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0035_auto_20161228_1940"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffJersey",
            fields=[
                (
                    "jersey_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="registration.Jersey",
                    ),
                ),
            ],
            bases=("registration.jersey",),
        ),
    ]
