# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:34


import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0054_auto_20170920_2254"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventEnd",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="eventStart",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
