# Generated by Django 2.2.25 on 2021-12-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0092_dealer_asst_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerasst",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
