# Generated by Django 3.2.18 on 2023-02-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0098_auto_20230124_2055"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentwebhooknotification",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
