# Generated by Django 5.1.5 on 2025-03-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0103_auto_20241109_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='htmlTemplatePath',
            field=models.CharField(default='', help_text='internal path to use for specifying which HTML templates to use for this event.', max_length=200, verbose_name='HTML Template Path'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginBottom',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Bottom'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginLeft',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Left'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginRight',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Right'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginTop',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Top'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='paperHeight',
            field=models.CharField(max_length=10, null=True, verbose_name='Paper Height'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='paperWidth',
            field=models.CharField(max_length=10, null=True, verbose_name='Paper Width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerPartnerPrice',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=6, verbose_name='Partner Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerWifi',
            field=models.BooleanField(default=True, help_text='Include option to purchase Wifi on dealers form', verbose_name='Dealer Wifi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerWifiPrice',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6, verbose_name='Wifi Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='defaultBadgeTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.badgetemplate', verbose_name='Badge Template'),
        ),
    ]
