# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 14:10


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_auto_20160821_1340"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="discount",
        ),
        migrations.AddField(
            model_name="order",
            name="charityDonation",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.Discount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="orgDonation",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
