# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0046_auto_20170427_1003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="charityDonation",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="orgDonation",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
    ]
