# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-19 08:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0086_rename_tables_squashed_0087_onsite_reg_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="firebase",
            name="background_color",
            field=models.CharField(default="#0099cc", max_length=10),
        ),
        migrations.AddField(
            model_name="firebase",
            name="foreground_color",
            field=models.CharField(default="#ffffff", max_length=10),
        ),
        migrations.AddField(
            model_name="firebase",
            name="webview",
            field=models.CharField(
                default=b"https://www.furthemore.org/code-of-conduct-embed/",
                max_length=500,
            ),
        ),
    ]
