# Generated by Django 3.2.25 on 2024-06-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0100_webhook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='signature_bitmap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='signature_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Captured', 'Captured'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Refund Pending', 'Refund Pending'), ('Failed', 'Failed'), ('Dispute Evidence Required', 'Dispute Evidence Required'), ('Dispute Processing', 'Dispute Processing'), ('Dispute Won', 'Dispute Won'), ('Dispute Lost', 'Dispute Lost'), ('Dispute Accepted', 'Dispute Accepted')], default='Pending', max_length=50),
        ),
    ]
