# Generated by Django 3.2.25 on 2024-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0101_auto_20240630_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="dealerPartnerPrice",
            field=models.DecimalField(decimal_places=2, default=55, max_digits=6),
        ),
        migrations.AddField(
            model_name="event",
            name="dealerWifi",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="dealerWifiPrice",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
    ]
