# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_squashed_0083_merge_20181224_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='Charity link', max_length=500, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='badgeTheme',
            field=models.CharField(default='apis', help_text='Name of badge theme to use for printing', max_length=200, verbose_name='Badge Theme'),
        ),
        migrations.AddField(
            model_name='event',
            name='codeOfConduct',
            field=models.CharField(blank=True, default='/code-of-conduct', help_text='Link to code of conduct agreement', max_length=500, verbose_name='Code of Conduct'),
        ),
        migrations.AddField(
            model_name='event',
            name='dealerEmail',
            field=models.CharField(blank=True, default=b'registration@example.com', help_text='Email to display on error messages for dealer registration', max_length=200, verbose_name='Dealer Email'),
        ),
        migrations.AddField(
            model_name='event',
            name='registrationEmail',
            field=models.CharField(blank=True, default=b'registration@example.com', help_text='Email to display on error messages for attendee registration', max_length=200, verbose_name='Registration Email'),
        ),
        migrations.AddField(
            model_name='event',
            name='staffEmail',
            field=models.CharField(blank=True, default=b'registration@example.com', help_text='Email to display on error messages for staff registration', max_length=200, verbose_name='Staff Email'),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='action',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Transaction', 'Transaction'), ('Deposit', 'Deposit')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Charity'),
        ),
    ]
