# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 01:14


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20160726_2342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="badgeNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="holdType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.HoldType",
            ),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.Attendee",
            ),
        ),
    ]
