# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-24 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_charity_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('issue_refund', 'Can create refunds'),)},
        ),
    ]
