# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 00:21


from datetime import datetime

import pytz
from django.db import migrations, models

PT = pytz.timezone("US/Pacific")


class Migration(migrations.Migration):

    DEFAULT_ORDER_MODIFIED_DATE = PT.localize(datetime.now())

    dependencies = [
        ("registration", "0003_auto_20160727_0114"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="createdDate", new_name="created",
        ),
        migrations.RemoveField(model_name="order", name="authorizationCode",),
        migrations.RemoveField(model_name="order", name="balance",),
        migrations.RemoveField(model_name="order", name="notes",),
        migrations.RemoveField(model_name="order", name="settledDate",),
        migrations.RemoveField(model_name="order", name="transactionId",),
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="department",
            name="volunteerListOk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_1",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_address_2",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_city",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_country_area",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_first_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_last_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_postcode",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="order",
            name="captured_amount",
            field=models.DecimalField(decimal_places=2, default="0.0", max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="customer_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.DecimalField(decimal_places=2, default="0.0", max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="extra_data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="fraud_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="fraud_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("accept", "Passed"),
                    ("reject", "Rejected"),
                    ("review", "Review"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="fraud check",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, default=DEFAULT_ORDER_MODIFIED_DATE
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for confirmation"),
                    ("preauth", "Pre-authorized"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("refunded", "Refunded"),
                    ("error", "Error"),
                    ("input", "Input"),
                ],
                default="waiting",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.DecimalField(decimal_places=2, default="0.0", max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="token",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default="0.0", max_digits=9),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="variant",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="priceleveloption",
            name="OptionExtraType",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
