# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20160729_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='priceLevel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.PriceLevel'),
        ),
    ]
