# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:33


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20160806_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeoptions",
            name="attendee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="registration.Attendee"
            ),
        ),
        migrations.AlterField(
            model_name="attendeeoptions",
            name="option",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.PriceLevelOption",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeoptions",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="registration.Order"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="attendee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="registration.Attendee"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.Discount",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="registration.Order"
            ),
        ),
    ]
