# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_event_collectbillingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apiData',
            field=models.TextField(blank=True),
        ),
    ]
