# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20160821_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeeoptions',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='attendeeoptions',
            name='order',
        ),
        migrations.AddField(
            model_name='attendeeoptions',
            name='orderItem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.OrderItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendeeoptions',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.PriceLevelOption'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Attendee'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Discount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='priceLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.PriceLevel'),
        ),
    ]
