# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20160828_1010"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="billing_address_1",),
        migrations.RemoveField(model_name="order", name="billing_address_2",),
        migrations.RemoveField(model_name="order", name="billing_city",),
        migrations.RemoveField(model_name="order", name="billing_country_area",),
        migrations.RemoveField(model_name="order", name="billing_country_code",),
        migrations.RemoveField(model_name="order", name="billing_email",),
        migrations.RemoveField(model_name="order", name="billing_first_name",),
        migrations.RemoveField(model_name="order", name="billing_last_name",),
        migrations.RemoveField(model_name="order", name="billing_postcode",),
        migrations.RemoveField(model_name="order", name="captured_amount",),
        migrations.RemoveField(model_name="order", name="created",),
        migrations.RemoveField(model_name="order", name="currency",),
        migrations.RemoveField(model_name="order", name="customer_ip_address",),
        migrations.RemoveField(model_name="order", name="delivery",),
        migrations.RemoveField(model_name="order", name="description",),
        migrations.RemoveField(model_name="order", name="extra_data",),
        migrations.RemoveField(model_name="order", name="fraud_message",),
        migrations.RemoveField(model_name="order", name="fraud_status",),
        migrations.RemoveField(model_name="order", name="message",),
        migrations.RemoveField(model_name="order", name="modified",),
        migrations.RemoveField(model_name="order", name="status",),
        migrations.RemoveField(model_name="order", name="tax",),
        migrations.RemoveField(model_name="order", name="token",),
        migrations.RemoveField(model_name="order", name="transaction_id",),
        migrations.RemoveField(model_name="order", name="variant",),
        migrations.AddField(
            model_name="attendee",
            name="registeredDate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="createdDate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order", name="notes", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="settledDate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="enteredDate",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
