# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 22:13


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0018_auto_20161010_1838"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="agreeToRules",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealer",
            name="artShow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealer", name="chairs", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dealer",
            name="charityRaffle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="extraTable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealer",
            name="reception",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dealer",
            name="shareWith",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dealer",
            name="tableSize",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.TableSize",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tablesize",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
