# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_remove_dealer_extratable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesize',
            name='chairMax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tablesize',
            name='chairMin',
            field=models.IntegerField(default=1),
        ),
    ]
