# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-20 23:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0023_auto_20161020_1843"),
    ]

    operations = [
        migrations.RemoveField(model_name="dealer", name="shareWith",),
        migrations.AddField(
            model_name="dealer", name="partners", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dealer", name="tables", field=models.IntegerField(default=0),
        ),
    ]
