# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-02 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0024_auto_20161020_1910"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablesize",
            name="basePrice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
