# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0025_tablesize_baseprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="buttonOffer",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
