# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0026_dealer_buttonoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="dealer",
            name="discountReason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
