# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-27 17:30


import datetime

import pytz
from django.db import migrations, models

PT = pytz.timezone("US/Pacific")


class Migration(migrations.Migration):

    DEFAULT_DATETIME = PT.localize(datetime.datetime.now())

    dependencies = [
        ("registration", "0033_discount_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendeeRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="attendeeRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="dealerRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="dealerRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="onlineRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="onlineRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="staffRegEnd",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="staffRegStart",
            field=models.DateTimeField(default=DEFAULT_DATETIME),
            preserve_default=False,
        ),
    ]
