# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_auto_20161230_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='number',
            field=models.CharField(max_length=3),
        ),
    ]
