# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0041_auto_20170217_1825"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="printed",
            field=models.BooleanField(default=False),
        ),
    ]
