# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-17 02:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0043_auto_20170310_2243"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendeeOnsite",
            fields=[],
            options={"proxy": True,},
            bases=("registration.attendee",),
        ),
        migrations.AddField(
            model_name="attendeeoptions",
            name="optionValue2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="attendeeoptions",
            name="optionValue3",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
