# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-27 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0044_auto_20170316_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="lastFour",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
