# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-27 14:03


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0045_order_lastfour"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeonsite",
            options={
                "verbose_name": "Attendee Onsite 2017",
                "verbose_name_plural": "Attendee Onsite 2017",
            },
        ),
        migrations.AddField(
            model_name="priceleveloption",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
