# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-19 00:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0049_auto_20170511_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="surveyOk",
            field=models.BooleanField(default=False),
        ),
    ]
