# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-15 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0051_orderitem_badge"),
    ]

    operations = [
        migrations.DeleteModel(name="AttendeeOnsite",),
        migrations.AddField(
            model_name="pricelevel",
            name="emailVIP",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricelevel",
            name="emailVIPEmails",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
    ]
