# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-21 02:54


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0053_auto_20170916_1047"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealer",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.Event",
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.Event",
            ),
        ),
    ]
