# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0057_tablesize_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(blank=True, max_length=200)),
                ("lastName", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
