# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_banlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='aslRequest',
            field=models.BooleanField(default=False),
        ),
    ]
