# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0059_attendee_aslrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dealerAsstDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerAsstDiscount_event', to='registration.Discount'),
        ),
        migrations.AddField(
            model_name='event',
            name='dealerDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerDiscount_event', to='registration.Discount'),
        ),
        migrations.AddField(
            model_name='event',
            name='staffDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffDiscount_event', to='registration.Discount'),
        ),
    ]
