# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-18 16:26


from django.db import migrations, models

import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0059_attendee_aslrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceleveloption",
            name="optionImage",
            field=models.ImageField(
                blank=True, null=True, upload_to=registration.models.content_file_name
            ),
        ),
    ]
