# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_cashdrawer_firebase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebase',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
