# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_auto_20180425_2022'),
        ('registration', '0060_priceleveloption_optionimage'),
    ]

    operations = [
    ]
