# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_auto_20180425_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=registration.models.getRegistrationToken, max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('validUntil', models.DateField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('usedDate', models.DateField()),
            ],
        ),
    ]
