# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_merge_20180726_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdrawer',
            name='action',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), (('Transaction',), 'Transaction'), ('Deposit', 'Deposit')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashdrawer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
