# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0067_auto_20180512_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temptoken',
            name='usedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
