# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 01:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0068_auto_20180802_2110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashdrawer",
            name="tendered",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="cashdrawer",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cashdrawer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
