# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0069_temptoken_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='newStaffDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newStaffEvent', to='registration.Discount'),
        ),
        migrations.AddField(
            model_name='event',
            name='staffDiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffEvent', to='registration.Discount'),
        ),
    ]
