# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0071_auto_20180721_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerAsst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationToken', models.CharField(default=registration.models.getRegistrationToken, max_length=200)),
                ('name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=200)),
                ('license', models.CharField(max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Attendee')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Dealer')),
            ],
        ),
    ]
