# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0073_dealerasst_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='checkedIn',
            field=models.BooleanField(default=False),
        ),
    ]
