# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0077_priceleveloption_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceleveloption',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
