# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0080_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ipAddress',
        ),
        migrations.AlterField(
            model_name='cart',
            name='form',
            field=models.CharField(choices=[('Attendee', 'Attendee'), ('Staff', 'Staff'), ('Dealer', 'Dealer'), ('Dealer Assistant', 'Dealer Assistant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='transferedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
