# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181224_1700'),
        ('registration', '0080_banlist_reason'),
    ]

    operations = [
    ]
