# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-31 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0080_banlist_reason'),
        ('registration', '0069_auto_20180802_2118'),
        ('registration', '0080_cart'),
    ]

    operations = [
    ]
