# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0081_auto_20181005_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='collectAddress',
            field=models.BooleanField(default=True, help_text='Disable to skip collecting a mailing address for each attendee.', verbose_name='Collect Address'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='allowOnlineMinorReg',
            field=models.BooleanField(default=False, help_text='Allow registration for anyone age 13 and older online. Otherwise, registration is restricted to those 18 or older.', verbose_name='Allow online minor registration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendeeRegEnd',
            field=models.DateTimeField(verbose_name='Attendee Registration End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendeeRegStart',
            field=models.DateTimeField(verbose_name='Attendee Registration Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerDiscount',
            field=models.ForeignKey(blank=True, help_text='Apply a discount for any dealer registrations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealerEvent', to='registration.Discount', verbose_name='Dealer Discount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerRegEnd',
            field=models.DateTimeField(verbose_name='Dealer Registration End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerRegStart',
            field=models.DateTimeField(help_text='Start date and time for dealer applications', verbose_name='Dealer Registration Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='default',
            field=models.BooleanField(default=False, help_text='The first default event will be used as the basis for all current event configuration', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventEnd',
            field=models.DateField(verbose_name='Event End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStart',
            field=models.DateField(verbose_name='Event Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='newStaffDiscount',
            field=models.ForeignKey(blank=True, help_text='Apply a discount for new staff registrations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newStaffEvent', to='registration.Discount', verbose_name='New Staff Discount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='onlineRegEnd',
            field=models.DateTimeField(verbose_name='On-site Registration End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='onlineRegStart',
            field=models.DateTimeField(help_text='Start time for /registration/onsite form', verbose_name='On-site Registration Start'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staffDiscount',
            field=models.ForeignKey(blank=True, help_text='Apply a discount for any staff registrations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffEvent', to='registration.Discount', verbose_name='Staff Discount'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staffRegEnd',
            field=models.DateTimeField(verbose_name='Staff Registration End'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staffRegStart',
            field=models.DateTimeField(help_text='(Not currently enforced)', verbose_name='Staff Registration Start'),
        ),
        migrations.AlterField(
            model_name='tablesize',
            name='description',
            field=models.TextField(),
        ),
    ]
