# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-07 08:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0082_auto_20181231_1519"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeoptions",
            options={
                "verbose_name": "Attendee option",
                "verbose_name_plural": "Attendee options",
            },
        ),
        migrations.AlterModelOptions(
            name="banlist", options={"verbose_name_plural": "Ban list"},
        ),
        migrations.AlterModelOptions(
            name="charity", options={"verbose_name_plural": "Charities"},
        ),
        migrations.AlterModelOptions(
            name="dealerasst",
            options={
                "verbose_name": "Dealer assistant",
                "verbose_name_plural": "Dealer assistants",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": (
                    ("issue_refund", "Can create refunds"),
                    ("cash", "Can handle cash transactions"),
                    ("cash_admin", "Can open and close cash drawer amounts (manager)"),
                    ("discount", "Can create discounts of arbitrary amount"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="priceleveloption",
            options={
                "verbose_name": "Price level option",
                "verbose_name_plural": "Price level options (merchandise)",
            },
        ),
        migrations.AlterModelOptions(
            name="shirtsizes", options={"verbose_name_plural": "Shirt sizes"},
        ),
        migrations.AlterModelOptions(
            name="staff", options={"verbose_name_plural": "Staff"},
        ),
        migrations.AddField(
            model_name="cashdrawer",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firebase_cashdrawer",
                to="registration.Firebase",
            ),
        ),
        migrations.AddField(
            model_name="firebase",
            name="printer_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="dealerEmail",
            field=models.CharField(
                blank=True,
                default=b"registration@example.com",
                help_text="Email to display on error messages for dealer registration",
                max_length=200,
                verbose_name="Dealer Email",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registrationEmail",
            field=models.CharField(
                blank=True,
                default=b"registration@example.com",
                help_text="Email to display on error messages for attendee registration",
                max_length=200,
                verbose_name="Registration Email",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="staffEmail",
            field=models.CharField(
                blank=True,
                default=b"registration@example.com",
                help_text="Email to display on error messages for staff registration",
                max_length=200,
                verbose_name="Staff Email",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingAddress1",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Address 1"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingAddress2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Address 2"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingCity",
            field=models.CharField(blank=True, max_length=200, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingCountry",
            field=models.CharField(blank=True, max_length=200, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingEmail",
            field=models.CharField(blank=True, max_length=200, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingName",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingPostal",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingState",
            field=models.CharField(blank=True, max_length=200, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingType",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("Credit", "Credit"),
                    ("Cash", "Cash"),
                    ("Comp", "Comp"),
                ],
                default="Credit",
                max_length=20,
                verbose_name="Billing Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="charityDonation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="Charity Donation",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="createdDate",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created Date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="lastFour",
            field=models.CharField(blank=True, max_length=4, verbose_name="Last 4"),
        ),
        migrations.AlterField(
            model_name="order",
            name="orgDonation",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                null=True,
                verbose_name="Organization Donation",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="settledDate",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Settled Date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Captured", "Captured"),
                    ("Completed", "Completed"),
                    ("Refunded", "Refunded"),
                    ("Refund Pending", "Refund Pending"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
