# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 02:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0083_auto_20200207_0355"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedBadgeNumbers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badgeNumber", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.Event",
                    ),
                ),
                (
                    "priceLevel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registration.PriceLevel",
                    ),
                ),
            ],
        ),
    ]
