# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0084_auto_20190507_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='useAuthToken',
            field=models.BooleanField(default=True, help_text='Toggle this setting off if you would like anyone with the staff registration URL to be able to sign up.', verbose_name='Use Auth Tokens'),
        ),
    ]
