# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0085_auto_20190509_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staffEventRegistration',
            field=models.BooleanField(default=False, help_text='If on, staff will be allowed to register for the event at the same time that they enter in their staff info.', verbose_name='Allow <i>event</i> registration at the same time as staff registration.'),
        ),
    ]
