# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-19 10:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0087_firebase_provision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firebase",
            name="webview",
            field=models.CharField(
                blank=True,
                default=b"https://www.furthemore.org/code-of-conduct-embed/",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tablesize", name="description", field=models.TextField(),
        ),
    ]
