# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-26 22:36


from django.db import migrations, models

import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0088_webview_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="signature_bitmap",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=registration.models.badge_signature_bitmap_path,
            ),
        ),
        migrations.AddField(
            model_name="badge",
            name="signature_svg",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=registration.models.badge_signature_svg_path,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="onsite_reference",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
