# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0088_auto_20190509_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='staffEventRegistration',
            field=models.BooleanField(default=False, help_text='If on, staff will be allowed to register for the event when they fill out the staff form.', verbose_name='Allow event registration as part of staff signup.'),
        ),
    ]
