# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0089_auto_20190509_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='staffEventRegistration',
            field=models.BooleanField(default=False, help_text='If on, staff will be allowed to register for the event when they fill out the staff form.', verbose_name='Allow event registration during staff signup.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='useAuthToken',
            field=models.BooleanField(default=True, help_text='Staff cannot register for the event (or take advantage of staff discounts) when auth tokens are not in use. ', verbose_name='Auth Tokens for Staff Registration '),
        ),
    ]
