# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0089_badge_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="dealerEmail",
            field=models.CharField(
                blank=True,
                default="registration@example.com",
                help_text="Email to display on error messages for dealer registration",
                max_length=200,
                verbose_name="Dealer Email",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registrationEmail",
            field=models.CharField(
                blank=True,
                default="registration@example.com",
                help_text="Email to display on error messages for attendee registration",
                max_length=200,
                verbose_name="Registration Email",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="staffEmail",
            field=models.CharField(
                blank=True,
                default="registration@example.com",
                help_text="Email to display on error messages for staff registration",
                max_length=200,
                verbose_name="Staff Email",
            ),
        ),
        migrations.AlterField(
            model_name="firebase",
            name="webview",
            field=models.CharField(
                blank=True,
                default="https://www.furthemore.org/code-of-conduct-embed/",
                max_length=500,
                null=True,
            ),
        ),
    ]
