# Generated by Django 2.2.24 on 2021-11-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0090_auto_20201214_2222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firebase",
            name="webview",
            field=models.CharField(
                blank=True,
                default="https://www.example.com/code-of-conduct-embed/",
                max_length=500,
                null=True,
            ),
        ),
    ]
