# Generated by Django 2.2.25 on 2021-12-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0091_alter_firebase_webview"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="assistantDiscount",
            field=models.ForeignKey(
                blank=True,
                help_text="Apply a discount for any dealer assistant registrations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistantEvent",
                to="registration.Discount",
                verbose_name="Dealer Assistant Discount",
            ),
        ),
    ]
