# Generated by Django 2.2.25 on 2021-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0092_auto_20211219_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venue',
            name='postalCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
