# Generated by Django 2.2.25 on 2022-01-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0093_add_dealerasst_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='preferredName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Preferred First Name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='firstName',
            field=models.CharField(max_length=200, verbose_name='Legal First Name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lastName',
            field=models.CharField(max_length=200, verbose_name='Legal Last Name'),
        ),
    ]
