# Generated by Django 3.2.16 on 2022-12-29 07:11

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    Order = apps.get_model("registration", "Order")
    for order in Order.objects.filter(apiData=""):
        order.apiData = None
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0095_add_cash_ledger_actions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integration", models.CharField(default="square", max_length=50)),
                ("event_id", models.UUIDField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("body", models.JSONField(verbose_name="Webhook body")),
                ("headers", models.JSONField(verbose_name="Webhook headers")),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="apiData",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.RunPython(blank_to_null),
        migrations.AlterField(
            model_name="order",
            name="apiData",
            field=models.JSONField(null=True),
        ),
    ]
