# Generated by Django 3.2.25 on 2025-02-17 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0105_add_trigram_extensions_20241114_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="firebase",
            name="terminal_token",
            field=models.CharField(
                blank=True, default=uuid.uuid4, max_length=500, null=True
            ),
        ),
    ]
