# Generated by Django 3.2.25 on 2025-03-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0105_add_trigram_extensions_20241114_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="firebase",
            name="print_via_mqtt",
            field=models.BooleanField(default=False, verbose_name='Print via MQTT'),
        ),
    ]
