# Generated by Django 3.2.25 on 2025-02-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0105_add_trigram_extensions_20241114_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginBottom',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Bottom'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginLeft',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Left'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginRight',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Right'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='marginTop',
            field=models.CharField(max_length=10, null=True, verbose_name='Margin Top'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='paperHeight',
            field=models.CharField(max_length=10, null=True, verbose_name='Paper Height'),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='paperWidth',
            field=models.CharField(max_length=10, null=True, verbose_name='Paper Width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerPartnerPrice',
            field=models.DecimalField(decimal_places=2, default=55, max_digits=6, verbose_name='Partner Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerWifi',
            field=models.BooleanField(default=True, help_text='Include option to purchase Wifi on dealers form', verbose_name='Dealer Wifi'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dealerWifiPrice',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6, verbose_name='Wifi Price'),
        ),
        migrations.AlterField(
            model_name='event',
            name='defaultBadgeTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.badgetemplate', verbose_name='Badge Template'),
        ),
        migrations.AlterField(
            model_name='priceleveloption',
            name='optionExtraType',
            field=models.CharField(blank=True, choices=[('int', 'Quantity'), ('bool', 'Yes/No'), ('ShirtSizes', 'Shirt Size'), ('string', 'String')], max_length=100),
        ),
    ]
