# Generated by Django 3.2.25 on 2025-02-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0105_add_trigram_extensions_20241114_1419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firebase",
            name="foreground_color",
        ),
        migrations.RemoveField(
            model_name="firebase",
            name="printer_url",
        ),
    ]
