# Generated by Django 3.2.25 on 2025-03-13 02:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0108_update_pricelevels"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquareDevice",
            fields=[
                (
                    "device_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("device_type", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="firebase",
            options={"verbose_name": "Terminal", "verbose_name_plural": "Terminals"},
        ),
        migrations.AddField(
            model_name="firebase",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("mqtt-app", "iPad"), ("square-terminal", "Square Terminal")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="firebase",
            name="cashdrawer",
            field=models.BooleanField(default=False, verbose_name="Cash drawer"),
        ),
        migrations.RemoveField(
            model_name="firebase",
            name="print_via_mqtt",
        ),
        migrations.AddField(
            model_name="firebase",
            name="print_via_mqtt",
            field=models.ForeignKey(
                blank=True,
                help_text="Which terminal to use for printing via MQTT, if it should be used at this terminal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.firebase",
                verbose_name="Print via MQTT",
            ),
        ),
        migrations.AlterField(
            model_name="firebase",
            name="token",
            field=models.CharField(default=uuid.uuid4, max_length=500),
        ),
        migrations.AlterField(
            model_name="firebase",
            name="webview",
            field=models.CharField(
                blank=True,
                default="https://www.example.com/code-of-conduct-embed/",
                max_length=500,
                null=True,
                verbose_name="Web view URL",
            ),
        ),
        migrations.AddField(
            model_name="firebase",
            name="square_terminal_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.squaredevice",
                verbose_name="Square Terminal",
            ),
        ),
    ]
