# Generated by Django 6.0.1 on 2026-02-04 00:06
import base64
import json

from django.db import migrations, connection


def convert_u2f_totp_entries(_apps, _schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'django_u2f_totpdevice'"
        )
        if cursor.fetchone() is None:
            return

        entries = []
        cursor.execute(
            "SELECT DISTINCT ON (user_id) created_at, last_used_at, user_id, key FROM django_u2f_totpdevice ORDER BY user_id, last_used_at DESC"
        )
        entries = cursor.fetchall()

        for entry in entries:
            cursor.execute(
                "INSERT INTO mfa_authenticator (type, created_at, last_used_at, user_id, data) VALUES ('totp', %s, %s, %s, %s) ON CONFLICT DO NOTHING",
                [
                    entry[0],
                    entry[1],
                    entry[2],
                    json.dumps({"secret": base64.b32encode(entry[3]).decode("ascii")}),
                ],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0110_print_via_payment"),
        ("mfa", "0003_authenticator_type_uniq"),
    ]

    operations = [
        migrations.RunPython(
            convert_u2f_totp_entries, reverse_code=lambda *_a, **_k: None
        )
    ]
