# Generated by Django 6.0.2 on 2026-03-03 04:25

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0113_remove_badge_printcount_printhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendeeoptions",
            name="optionValue2",
        ),
        migrations.RemoveField(
            model_name="attendeeoptions",
            name="optionValue3",
        ),
        migrations.RemoveField(
            model_name="priceleveloption",
            name="optionExtraType2",
        ),
        migrations.RemoveField(
            model_name="priceleveloption",
            name="optionExtraType3",
        ),
        migrations.AddField(
            model_name="attendeeoptions",
            name="fulfilled_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="attendeeoptions",
            name="fulfilled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="priceleveloption",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="priceleveloption",
            name="requires_fulfillment",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="charityDonation",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Charity Donation",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="orgDonation",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Organization Donation",
            ),
        ),
    ]
