# Generated by Django 6.0.3 on 2026-04-04 06:55
import itertools
import json
import logging
import re

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

logger = logging.getLogger(__name__)


def _event_name_from_repr(object_repr):
    match = re.search(r"\(([^)]+)\)$", object_repr)
    return match.group(1) if match else None


def _entry_changes_event(change_message):
    try:
        changes = json.loads(change_message)
        for change in changes:
            fields = change.get("changed", {}).get("fields", [])
            if any(f.lower() == "event" for f in fields):
                return True
    except (json.JSONDecodeError, TypeError, AttributeError):
        return False
    return False


def _event_from_registration_date(badge, Event):
    if not badge.registeredDate:
        return None

    reg_dt = badge.registeredDate

    return (
        Event.objects.filter(
            attendeeRegStart__lte=reg_dt,
            eventEnd__gte=reg_dt.date(),
        )
        .order_by("eventStart")
        .first()
    )


def backfill_roll_forwards(apps, _schema_editor):
    Badge = apps.get_model("registration", "Badge")
    Event = apps.get_model("registration", "Event")
    BadgeRollForward = apps.get_model("registration", "BadgeRollForward")
    LogEntry = apps.get_model("admin", "LogEntry")
    ContentType = apps.get_model("contenttypes", "ContentType")

    try:
        badge_ct = ContentType.objects.get(app_label="registration", model="badge")
    except ContentType.DoesNotExist:
        logger.warning("Badge content type does not exist, skipping backfill")
        return

    events_by_name = {e.name: e for e in Event.objects.all()}

    entries = LogEntry.objects.filter(
        content_type=badge_ct,
        action_flag=2,
    ).order_by("object_id", "action_time")

    groups = itertools.groupby(entries, key=lambda entry: entry.object_id)

    for badge_id, badge_entries in groups:
        badge_entries = list(badge_entries)

        try:
            badge = Badge.objects.get(pk=badge_id)
        except Badge.DoesNotExist:
            logger.warning("Badge pk=%s in log no longer exists, skipping", badge_id)
            continue

        for idx, entry in enumerate(badge_entries):
            if not _entry_changes_event(entry.change_message):
                continue

            to_event_name = _event_name_from_repr(entry.object_repr)
            if not to_event_name:
                logger.warning(
                    "Badge pk=%s could not parse event name from object_repr %r, skipping",
                    badge_id,
                    entry.object_repr,
                )
                continue

            to_event = events_by_name.get(to_event_name)
            if to_event is None:
                logger.warning(
                    "Badge pk=%s to_event %r not found in database, skipping",
                    badge_id,
                    to_event_name,
                )
                continue

            if idx > 0:
                from_event_name = _event_name_from_repr(
                    badge_entries[idx - 1].object_repr
                )
                from_event = (
                    events_by_name.get(from_event_name) if from_event_name else None
                )
                if from_event is None:
                    logger.warning(
                        "Badge pk=%s from_event %r (from prior log repr) not found in database, skipping",
                        badge_id,
                        from_event_name,
                    )
                    continue
            else:
                from_event = _event_from_registration_date(badge, Event)
                if from_event is None:
                    logger.warning(
                        "Badge pk=%s first log entry is an event change but could not determine from_event from registeredDate %s, skipping",
                        badge_id,
                        badge.registeredDate,
                    )
                    continue
                logger.info(
                    "Badge pk=%s inferred from_event %r from registeredDate %s",
                    badge_id,
                    from_event.name,
                    badge.registeredDate,
                )

            if from_event == to_event:
                logger.debug(
                    "Badge pk=%s from_event and to_event are both %r, skipping",
                    badge_id,
                    to_event_name,
                )
                continue

            if BadgeRollForward.objects.filter(
                badge=badge,
                from_event=from_event,
                to_event=to_event,
            ).exists():
                logger.debug(
                    "Badge pk=%s roll forward %r -> %r already recorded, skipping",
                    badge_id,
                    from_event.name,
                    to_event.name,
                )
                continue

            roll = BadgeRollForward.objects.create(
                badge=badge,
                from_event=from_event,
                to_event=to_event,
                rolled_by_id=entry.user_id or None,
            )
            roll.rolled_at = entry.action_time
            roll.save()
            logger.info(
                "Badge pk=%s recorded roll forward %r -> %r on %s",
                badge_id,
                from_event.name,
                to_event.name,
                entry.action_time,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0116_alter_staffinvite_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BadgeRollForward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roll_forwards",
                        to="registration.badge",
                    ),
                ),
                (
                    "from_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="registration.event",
                        verbose_name="From event",
                    ),
                ),
                (
                    "rolled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rolled by",
                    ),
                ),
                (
                    "to_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="registration.event",
                        verbose_name="To event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Badge roll forward",
                "verbose_name_plural": "Badge roll forwards",
                "db_table": "registration_badge_roll_forward",
            },
        ),
        migrations.RunPython(
            backfill_roll_forwards,
            migrations.RunPython.noop,
        ),
    ]
