# Generated by Django 6.0.3 on 2026-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0116_alter_staffinvite_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firebase",
            name="print_via_payment",
        ),
        migrations.AddField(
            model_name="firebase",
            name="print_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("station", "Station Service"),
                    ("mqtt-app", "iPad"),
                    ("web-usb", "WebUSB"),
                ],
                help_text="Which device at the selected terminal to use for printing badges.",
                max_length=20,
                verbose_name="Print Target",
            ),
        ),
    ]
