# Generated by Django 6.0.6 on 2026-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0118_badge_roll_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebase',
            name='web_access',
            field=models.BooleanField(default=False, help_text="Allow this terminal's token to perform web-like actions.", verbose_name='Web access'),
        ),
    ]
