# Generated by Django 6.0.7 on 2026-07-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0119_badge_staff_badge_badge_attendee_or_staff_not_both'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='twitter',
            new_name='bluesky',
        ),
    ]
