# Generated by Django 5.1.5 on 2025-03-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furpocalypse_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='htmlTemplatePath',
            field=models.CharField(blank=True, default='', help_text='internal path to use for specifying which HTML templates to use for this event.', max_length=200, verbose_name='HTML Template Path'),
        ),
    ]
