## /etc/mosquitto/conf.d/apis.conf

per_listener_settings false
allow_anonymous false

## https://github.com/wiomoc/mosquitto-jwt-auth

auth_plugin /etc/mosquitto/auth/libmosquitto_jwt_auth.so
auth_opt_jwt_alg HS256
# Populate this value with a strong, randomly-generated base64 secret used for JWT signing:
auth_opt_jwt_sec_base64 supersecret==
auth_opt_jwt_validate_exp false
auth_opt_jwt_validate_sub_match_username false


## MQTT and TLS listeners
listener 1883
listener 8883

# Automatic certificates can be obtained using an ACME client with DNS-0 challenge, e.g. Lego
cafile /etc/ssl/certs/ca-certificates.crt

certfile /etc/mosquitto/certs/_.mqtt.furthemore.org.crt
keyfile  /etc/mosquitto/certs/_.mqtt.furthemore.org.key

# Reverse proxy this port with your webserver to make this transport available as a websocket
listener 1884 127.0.0.1
protocol websockets
