name: Build Documentation

on:
  push:
    branches: [ production, stage ]
  pull_request:
    branches: [ production, stage ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        sudo apt-get -y install python3-psycopg2
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Generate mermaid docs
      run: |
        cp fm_eventmanager/settings.py.travis fm_eventmanager/settings.py
        wget https://raw.githubusercontent.com/Mr-Destructive/django-mermaid/main/mermaid.py
        python mermaid.py fm_eventmanager
        mkdir -p docs/
        mv fm_eventmanager_model.md docs/
        rm mermaid.py
      env:
        SQUARE_APPLICATION_ID: ${{ secrets.SQUARE_APPLICATION_ID }}
        SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
        SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    - name: Commit mermaid docs back to branch
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'docs'

        # Determines the way the action fills missing author name and email. Three options are available:
        # - github_actor -> UserName <UserName@users.noreply.github.com>
        # - user_info -> Your Display Name <your-actual@email.com>
        # - github_actions -> github-actions <email associated with the github logo>
        # Default: github_actor
        default_author: github_actor

        # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
        # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ.
        # Default: --tags --force
        fetch: false

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Generate mermaid graph of Django model'
