name: Django CI

on:
  push:
    branches: [production, stage]
  pull_request:
    branches: [production, stage]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.13", "3.14"]

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:17
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

      gotenberg:
        image: gotenberg/gotenberg:8
        options: >-
          --health-cmd "curl --fail http://localhost:3000/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3000:3000

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Login to Docker Hub (read-only)
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Dependencies
        run: |
          uv sync
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
      - name: Build frontend
        run: |
          cd registration/frontend
          npm install
          npm run build
      - name: Run Tests
        run: |
          cp fm_eventmanager/settings.py.ci fm_eventmanager/settings.py
          uv run python ./manage.py collectstatic --noinput --skip-checks
          uv run coverage run ./manage.py test registration
        env:
          SQUARE_APPLICATION_ID: ${{ secrets.SQUARE_APPLICATION_ID }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
          SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      - name: Submit coverage
        run: uv run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
