name: Build & Deploy

on:
  # Manually triggered from the UI
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: environment

  # Dependency to a forking workflow
  #workflow_run:
  #  workflows: ["Django CI"]
  #  types: [completed]

permissions: {}

jobs:
  build_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: ${{ github.event.inputs.environment }}
    concurrency: ${{ github.event.inputs.environment }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false
    - name: Login to packages container registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      env:
        DEPLOY_ENV: ${{ github.event.inputs.environment }}
      run: |
        make build-docker-image
        make "tag-${DEPLOY_ENV}"

    - name: Deploy to server
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
      env:
        DEPLOY_ENV: ${{ github.event.inputs.environment }}
      with:
        host: maaa-registration
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.SSH_HOST }}
        proxy_username: ${{ secrets.SSH_USERNAME }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: DEPLOY_ENV
        script: |
          cd /opt/docker
          docker-compose pull
          docker-compose up -d "apis-${DEPLOY_ENV}" "apis-${DEPLOY_ENV}-worker"
