name: Build docker image and push to repo

on:
  # Manually triggered from the UI
  workflow_dispatch:
    inputs:
      message:
        description: "Build & Deploy"

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["Django CI"]
    types: [completed]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    environment: stage
    concurrency: stage
    steps:
    - uses: actions/checkout@v2
    - name: Login to packages container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: nelonoel/branch-name@v1.0.1
    - name: Build image
      run: |
        make build-docker-image
        make tag-${BRANCH_NAME}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: maaa-registration
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: ${{ secrets.SSH_HOST }}
        proxy_username: ${{ secrets.SSH_USERNAME }}
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/docker
          docker-compose pull
          docker-compose up -d
          docker-compose exec -T apis-stage ./manage.py migrate
          #docker-compose exec -T apis-prod./manage.py migrate
